### PR TITLE
Various enchantments

### PR DESCRIPTION
**Pull request by TheCryoknight**
- Add proper tab completion to Modules Command
- Add colors and other clarifying information to Modules Command
- JavaDoc clarification in Afk Manager
- Externalise greylist commands to Greylist Helper
- Remove unneeded and unnecessary permission checks in the Asshat Module (Bukkit already checks when they are defined in the plugin.yml)

### CODE REVIEW

**Comment by nristock** [comment]
I left some notes... and I have some more stuff in mind:
What about renaming PlayerGreylistEvent to something like PrePlayerGreylistEvent? ...I think that would make more sense.
I think the GreylistHelper class methods can be made static since it is really just a utility class.

**Comment by TheCryoknight** [comment]
Can this me merged now?

**Comment by nristock** [comment]
Haven't had time to review it, yet.

**Comment by itsjoekent** [comment]
Someones in a rush :p

**Pull request merged**
