### PR TITLE
Updated ChatEvent for new BukkitAPI

### PR DESCRIPTION
**Pull request by itsjoekent**
Fixes this: http://pastebin.com/MMbn6geE
(Reported by Cisco)

### CODE REVIEW

**Comment by psanker** [comment]
Not really. Besides, if you want to change everything to the async event, much refactoring would need to take place.

**Comment by itsjoekent** [comment]
Only chat is async because chat runs on its own thread. Open this up in you're IDE, it will even tell you it's deprecated. Using this old method has chat lag, as stated by EvilSeph. Thus they added this, I can get proof if you need it but this should really be updated.

EDIT:
https://github.com/Bukkit/CraftBukkit/commit/ecf4ec691eb26ea4b68284691d086f0fa8561c74
https://github.com/Bukkit/Bukkit/commit/e49a640760a738ed79c9719a0d6959038fb3c0ba

That is explicitly says this causes lag, and shouldn't be used. Also, iSay should update to this as well, other wise when we update it won't be to pretty...

**Comment by psanker** [comment]
Chat lag ≠ lag. I'm well aware of the new events.

**Comment by itsjoekent** [comment]
Okay, but why are we having 2 major plugins running on deprecated events on an API where the lead devs said not to use that event & use what I suggested...

**Comment by psanker** [comment]
Because I have yet to determine if the async event works properly.

**Comment by itsjoekent** [comment]
Working 1.3 Chat Plugin
http://dev.bukkit.org/server-mods/channel-chat/
Using the async event
https://github.com/ChannelChat/Channel-Chat/blob/master/src/main/java/com/feildmaster/channelchat/listener/ChatListener.java

Which is written by a Bukkit Dev. If you really need too I can just test it in 5 minutes, but due to the fact it's our only option (Because using a deprecated event that causes chat lag is a really bad idea) I'm trying to figure out why were having a problem with this...

**Comment by MikeMatrix** [comment]
Because determining the synchronization requirements for an Asynchronous System is a must do.
Don't just run around changing things, because you think it's correct.
Since the Lead Developer of this plugin is psanker, you should respect his decision to not change it to this, because he has yet to look into those things.
I can fully understand and support his decision to not pull this in yet.

**Pull request closed without merging**
