### PR TITLE
Fix for build issues

### PR DESCRIPTION
**Pull request by BlockCat**
I'm sorry, I deleted and pasted the wrong lines...
now it's fixed.

### CODE REVIEW

**Comment by BlockCat** [comment]
I think it is fine to merge this as it is such a small correction?

**Comment by itsjoekent** [comment]
http://thevoxelbox.com/forum/writin-codez-f42/coding-guidelines-t1395.html

Mike, Me, Mono, Psank, Prz, a lot of people could have merged it. Even if it's a small change, it's going to turn into a bad habit. we would have merged this anyway, and it's not like this is urgent and it's being thrown on the server this very moment, so why did you do it?

But this is mikes place to say, im just puttin my 2 cents in.

**Comment by itsjoekent** [comment]
Also, didn't you test this? If something in the code doesn't work it wouldn't have functioned in-game.

**Comment by BlockCat** [comment]
I did test it, but I deleted the wrong line when putting it over to github.
I still have problems with installing Egit, so I put the code manually in github.

**Comment by itsjoekent** [comment]
Don't edit the code on github. Do it from your PC, there's many tutorials out there, if you can't get whatever your using to work try something else.

**Comment by BlockCat** [comment]
Already fixed it!
I decided to spend the whole day making it work.

**Pull request merged**
