### PR TITLE
Fixed painting popping and wither spawning

### PR DESCRIPTION
**Pull request by Billyyjoee**

### CODE REVIEW

**Comment by nristock** [comment]
Oh wow. Can't really check this from my mobile device anymore :P will do it when I'm home again.

**Comment by itsjoekent** [comment]
Its christmas guys, we can stop coding for one day: p

**Comment by nristock** [comment]
C'mon that was only one click for me.  Also, merry Christmas :)

**Comment by itsjoekent** [comment]
: p 

Happy holidays!

**Pull request merged**
